### ISSUE TITLE
Criação das Estimativas

### ISSUE THREAD

**Issue by tomasvelos0** [UnBArqDsw2021-1/2021.1_G04_Cardeal#10]
Criação da Página sobre Estimativas do projeto

**Comment by gustavoduartemoreira** [comment]
Tomas, 
Olhei o texto das estimativas e verifiquei esses erros de digitação:
Com o entendimento da "prosta" inicial e detalhamento do projeto, -> deve ser proposta

Como todos os membros da equipe "irá" participar de todo o projeto pelo tempo estimado de 4 meses -> acredito que o verbo deve concordar com todos "irão" ficando "todos os membros da equipe "irão" 

qdo puder dá um confere lá!

**Comment by tomasvelos0** [comment]
Obrigado Gustavo,
Realizei as correções.
