### ISSUE TITLE
Estilizar a página da Wiki

### ISSUE THREAD

**Issue by estevaoreis25** [UnBArqDsw2021-1/2021.1_G04_Cardeal#3]

**Comment by brunocmo** [comment]
## Instalação do jekyll na sua máquina
https://jekyllrb.com/docs/installation/
## Como rodar localmente
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
## Informações adicionais de como executar localmente
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

**Comment by tomasvelos0** [comment]
**Instalação**

Use o comando:

`pip install mkdocs`

Para verificar se tudo deu certo, execute esse comando:

`mkdocs --version`

Deve estar na versão: version 1.2.2

Após a instalação do mkdocs, necessita instalar o nosso tema, utilizando o comando:

`pip install mkdocs-gitbook`

Para iniciar a página, entra no local onde a pasta do projeto foi clonada e executa o comando:

`mkdocs serve`

**Comment by marcos-mv** [comment]
Para realizar o deploy das suas mudanças nos documentos, verifique se não existe nenhuma divergência na main  utilize o comando dentro da branch main:  
`mkdocs build `
 e depois o comando 
 `mkdocs gh-deploy` .
