### ISSUE TITLE
Segunda Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-1/2021.1_G04_Cardeal#89]
Olá Pessoal!

O Grupo 04 irá avaliar o Grupo 03 nessa segunda avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta acessar o Tópico 2 DSW(Modelagem) no Moodle, e procurar por "Segunda Avaliação por Pares".

Deadline: 27 de Agosto de 2021, ao final do dia, conforme consta no cronograma.

Atenciosamente.

**Comment by gustavoduartemoreira** [comment]
Avaliação realizada em grupo no dia 27 de Agosto.
